#Build image base

# Sử dụng image chứa Python 3.7
FROM python:3.10.11
WORKDIR /app
# # Cài đặt các gói phần mềm bằng pip

RUN apt-get update
RUN apt-get update && apt-get install -y wget gnupg2
# Tải và cài đặt Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update && apt-get install -y google-chrome-stable
# Chạy lệnh này để tránh lỗi khi chạy Chrome trong container
RUN echo "export DBUS_SESSION_BUS_ADDRESS=/dev/null" >> ~/.bashrc
# Đặt Chrome làm trình duyệt mặc định
RUN update-alternatives --install /usr/bin/google-chrome google-chrome /usr/bin/google-chrome-stable 100

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#CMD [ "python", "app.py" ]
