#Build image base

# Sử dụng image chứa Python 3.7
FROM python:3.10.11
WORKDIR /app
# # Cài đặt các gói phần mềm bằng pip
RUN apt-get update
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#CMD [ "python", "app.py" ]
